namespace Redux.Enum
{
    public enum DataAction:ushort
    {
        SetLocation = 74,
        Hotkeys = 75,
        ConfirmFriends = 76,
        ConfirmProficiencies = 77,
        ConfirmSkills = 78,
        ChangeDirection = 79,
        ChangeAction = 81,
        UsePortal = 85,
        Teleport = 86,
        Leveled = 92,
        RemoveXp = 93,
        Revive = 94,
        Delete = 95,
        ChangePKMode = 96,
        ConfirmGuild = 97,
        Mine = 99,
        InvisibleEntity = 102,
        ScreenColor = 104,
        TeamateLoc = 106,
        NewCoordinates = 108,
        DropMagic = 109,
        DropSkill = 110,
        Vend = 111,
        GetSurroundings = 114,
        OpenCustom = 116,
        ObserveEquipment = 117,
        CancelDisguise = 118,
        CancelFly = 120,
        GoldPickup = 121,
        EnemyInfo = 123,
        OpenWindow = 126,
        CompleteLogin = 130,
        SpawnEffect = 131,
        RemoveEntity = 132,
        Jump = 133,
        SetGhost = 137,
        FriendInfo = 140,
        ChangeFace = 142,
        EndTeleport = 146,
        ItemsDetained = 154,
        DetainItems = 155,
        Shift = 156,
        HideInterface = 158,
        BlueCountdown = 159,
        OpenUpgrade = 160,
        PathFind = 162, 
        AbortMagic = 163,
        MapARGB = 164,
        MobDropsDragonball = 165,
        ObserveFriend = 310
    }
}
